name: "Run isort"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest]
        python-version: [  "3.10" ]
        pytorch-version: [ "1.12.0" ]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: iterative/setup-dvc@v1

    - name: Get data
      run: dvc pull
      env:
        GDRIVE_CREDENTIALS_DATA: $
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install isort
      run: pip install isort
    - name: Test with isort
      run: isort src